return {
	"pmizio/typescript-tools.nvim",
	ft = { "typescript", "typescriptreact", "javascript", "javascriptreact" },
	opts = {
		on_attach = function(client)
			client.server_capabilities.documentFormattingProvider = false
			client.server_capabilities.documentRangeFormattingProvider = false
		end,
		settings = {
			tsserver_file_preferences = {
				quotePreference = "auto",
				importModuleSpecifierEnding = "auto",
				jsxAttributeCompletionStyle = "auto",
				allowTextChangesInNewFiles = true,
				providePrefixAndSuffixTextForRename = true,
				allowRenameOfImportPath = true,
				includeAutomaticOptionalChainCompletions = true,
				provideRefactorNotApplicableReason = true,
				generateReturnInDocTemplate = true,
				includeCompletionsForImportStatements = true,
				includeCompletionsWithSnippetText = true,
				includeCompletionsWithClassMemberSnippets = true,
				includeCompletionsWithObjectLiteralMethodSnippets = true,
				useLabelDetailsInCompletionEntries = true,
				allowIncompleteCompletions = true,
				displayPartsForJSDoc = true,
				disableLineTextInReferences = true,
				includeInlayParameterNameHints = "all",
				includeInlayParameterNameHintsWhenArgumentMatchesName = true,
				includeInlayFunctionParameterTypeHints = true,
				includeInlayVariableTypeHints = true,
				includeInlayVariableTypeHintsWhenTypeMatchesName = true,
				includeInlayPropertyDeclarationTypeHints = true,
				includeInlayFunctionLikeReturnTypeHints = true,
				includeInlayEnumMemberValueHints = true,
			},
			separate_diagnostic_server = false,
			publish_diagnostic_on = "insert_leave",
			expose_as_code_action = {},
			tsserver_max_memory = "auto",
			tsserver_locale = "fr",
			complete_function_calls = true,
			include_completions_with_insert_text = true,
			code_lens = "off",
			disable_member_code_lens = true,
		},
	},
	dependencies = {
		{ "nvim-lua/plenary.nvim", lazy = true },
		{ "neovim/nvim-lspconfig", lazy = true },
	},
}
