-- ── which-key.nvim ───────────────────────────────────────────────────────
-- Purpose : Keymap discovery popup — shows available keybindings when you
--           pause on a prefix key. Reads all existing desc fields automatically.
-- Trigger : VeryLazy
-- Theme   : Catppuccin Mocha via integrations.which_key = true in catppuccin.lua
-- Note    : No mapping changes needed — all existing keymaps already have desc.
--           <leader>? shows all keymaps for the current buffer.
-- ─────────────────────────────────────────────────────────────────────────
---@type LazySpec
return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	opts = {
		preset = "helix",
		icons = {
			mappings = true,
			-- keys = {} would strip all modifier-key glyphs (⌃, ⌥, ⇧, etc.)
			-- Leave unset to keep which-key's built-in Nerd Font key icons
			group = "",
			-- Icon rules: matched against keymap desc in order, first match wins.
			-- Covers all custom function() keymaps that mini.icons can't auto-resolve.
			rules = {
				-- ── Find / Search ──────────────────────────────────────────
				{ pattern = "find files", icon = "󰈞", color = "blue" },
				{ pattern = "live grep", icon = "󰺮", color = "blue" },
				{ pattern = "grep", icon = "󰺮", color = "blue" },
				{ pattern = "find", icon = "󰍉", color = "blue" },
				{ pattern = "search", icon = "󰱼", color = "blue" },
				{ pattern = "buffer lines", icon = "󰈙", color = "blue" },
				{ pattern = "recent files", icon = "󱋡", color = "blue" },
				{ pattern = "buffers", icon = "󰈙", color = "azure" },
				{ pattern = "marks", icon = "󰃀", color = "yellow" },
				{ pattern = "registers", icon = "󱄻", color = "yellow" },
				{ pattern = "command history", icon = "󰋚", color = "purple" },
				{ pattern = "commands", icon = "󰘳", color = "purple" },
				{ pattern = "icons", icon = "󰀻", color = "yellow" },
				{ pattern = "highlights", icon = "󰸱", color = "yellow" },
				{ pattern = "keymaps", icon = "󰌌", color = "azure" },
				{ pattern = "autocommands", icon = "󱐋", color = "azure" },
				{ pattern = "help tags", icon = "󰋖", color = "azure" },
				{ pattern = "help grep", icon = "󰋖", color = "azure" },
				{ pattern = "todo", icon = "󰄵", color = "yellow" },
				{ pattern = "notification", icon = "󰂱", color = "yellow" },
				{ pattern = "jump list", icon = "󰌑", color = "azure" },
				{ pattern = "undo", icon = "󰕌", color = "azure" },
				-- ── Git ────────────────────────────────────────────────────
				{ pattern = "git status", icon = "󰊢", color = "orange" },
				{ pattern = "git log", icon = "󰜘", color = "orange" },
				{ pattern = "git commits", icon = "󰜘", color = "orange" },
				{ pattern = "git branches", icon = "󰘬", color = "orange" },
				{ pattern = "git browse", icon = "󰖟", color = "orange" },
				{ pattern = "git worktree", icon = "󰙅", color = "orange" },
				{ pattern = "git conflict", icon = "󰩹", color = "red" },
				{ pattern = "gitsigns toggle blame", icon = "󰊢", color = "orange" },
				{ pattern = "gitsigns toggle word diff", icon = "󰦓", color = "orange" },
				{ pattern = "gitsigns stage", icon = "󰐖", color = "green" },
				{ pattern = "gitsigns reset", icon = "󰦛", color = "red" },
				{ pattern = "gitsigns preview", icon = "󰈈", color = "orange" },
				{ pattern = "gitsigns blame", icon = "󰊢", color = "orange" },
				{ pattern = "gitsigns", icon = "󰊢", color = "orange" },
				{ pattern = "lazygit", icon = "󰊢", color = "green" },
				{ pattern = "codediff", icon = "󰦓", color = "orange" },
				{ pattern = "worktree", icon = "󰙅", color = "orange" },
				{ pattern = "github auth", icon = "󰊤", color = "grey" },
				-- ── LSP ────────────────────────────────────────────────────
				{ pattern = "lsp references", icon = "󰈇", color = "blue" },
				{ pattern = "lsp reference", icon = "󰈇", color = "blue" },
				{ pattern = "lsp signature", icon = "󰊕", color = "blue" },
				{ pattern = "lsp hover", icon = "󰋖", color = "blue" },
				{ pattern = "lspsaga hover", icon = "󰋖", color = "blue" },
				{ pattern = "lspsaga finder", icon = "󰍉", color = "blue" },
				{ pattern = "lspsaga code actions", icon = "󰌵", color = "yellow" },
				{ pattern = "lspsaga peek", icon = "󰈈", color = "blue" },
				{ pattern = "lspsaga goto", icon = "󰆼", color = "blue" },
				{ pattern = "lspsaga.*implementation", icon = "󰡱", color = "blue" },
				{ pattern = "lspsaga rename", icon = "󰑕", color = "yellow" },
				{ pattern = "rename", icon = "󰑕", color = "yellow" },
				{ pattern = "lspsaga outline", icon = "󱒎", color = "blue" },
				{ pattern = "lspsaga.*calls", icon = "󰊕", color = "blue" },
				{ pattern = "lspsaga.*diagnostic", icon = "󰒡", color = "red" },
				{ pattern = "diagnostics", icon = "󰒡", color = "red" },
				{ pattern = "ts organize imports", icon = "󰋺", color = "blue" },
				{ pattern = "ts add missing imports", icon = "󰐗", color = "blue" },
				{ pattern = "ts remove unused imports", icon = "󰍷", color = "red" },
				{ pattern = "ts fix", icon = "󰁨", color = "blue" },
				{ pattern = "ts file references", icon = "󰈇", color = "blue" },
				{ pattern = "ts implementations", icon = "󰡱", color = "blue" },
				{ pattern = "ts rename file", icon = "󰑕", color = "yellow" },
				{ pattern = "mason", icon = "󱌣", color = "blue" },
				-- ── DAP / Debug ────────────────────────────────────────────
				{ pattern = "dap.*toggle.*breakpoint", icon = "󰝥", color = "red" },
				{ pattern = "dap.*continue", icon = "󰐊", color = "green" },
				{ pattern = "dap.*terminate", icon = "󰓛", color = "red" },
				{ pattern = "dap step over", icon = "󰆷", color = "yellow" },
				{ pattern = "dap step into", icon = "󰆹", color = "yellow" },
				{ pattern = "dap step out", icon = "󰆸", color = "yellow" },
				{ pattern = "dap run to cursor", icon = "󰐊", color = "green" },
				{ pattern = "dapui", icon = "󰃤", color = "purple" },
				{ pattern = "dap", icon = "󰃤", color = "purple" },
				{ pattern = "debug", icon = "󰃤", color = "purple" },
				-- ── Test ───────────────────────────────────────────────────
				{ pattern = "neotest run", icon = "󰙨", color = "green" },
				{ pattern = "neotest debug", icon = "󰃤", color = "purple" },
				{ pattern = "neotest.*summary", icon = "󰋖", color = "blue" },
				{ pattern = "neotest.*output", icon = "󰉸", color = "azure" },
				{ pattern = "neotest.*failed", icon = "󰅙", color = "red" },
				{ pattern = "neotest stop", icon = "󰓛", color = "red" },
				{ pattern = "next failed", icon = "󰅙", color = "red" },
				{ pattern = "prev failed", icon = "󰅙", color = "red" },
				-- ── Format / Lint ──────────────────────────────────────────
				{ pattern = "format buffer", icon = "󰉢", color = "blue" },
				{ pattern = "codespell", icon = "󰓆", color = "yellow" },
				-- ── File / Explorer ────────────────────────────────────────
				{ pattern = "neotree", icon = "󰙅", color = "green" },
				{ pattern = "explorer", icon = "󰉋", color = "green" },
				{ pattern = "file system", icon = "󰝰", color = "green" },
				-- ── Terminal / REPL ────────────────────────────────────────
				{ pattern = "terminal", icon = "󰆍", color = "green" },
				{ pattern = "iron.*repl", icon = "󰘞", color = "cyan" },
				{ pattern = "repl", icon = "󰘞", color = "cyan" },
				-- ── AI / CodeCompanion ─────────────────────────────────────
				{ pattern = "codecompanion", icon = "󰚩", color = "green" },
				-- ── Database / Dadbod ─────────────────────────────────────
				{ pattern = "dbui", icon = "󰆼", color = "cyan" },
				{ pattern = "database", icon = "󰆼", color = "cyan" },
				-- ── HTTP / Kulala ──────────────────────────────────────────
				{ pattern = "kulala run", icon = "󰖟", color = "blue" },
				{ pattern = "kulala", icon = "󰖟", color = "azure" },
				-- ── Overseer / Tasks ───────────────────────────────────────
				{ pattern = "overseer", icon = "󰑮", color = "yellow" },
				{ pattern = "task", icon = "󰄵", color = "yellow" },
				-- ── UI ─────────────────────────────────────────────────────
				{ pattern = "trouble", icon = "󰒡", color = "red" },
				{ pattern = "noice dismiss", icon = "󰅖", color = "purple" },
				{ pattern = "noice", icon = "󰍡", color = "purple" },
				{ pattern = "notify dismiss", icon = "󰂱", color = "yellow" },
				{ pattern = "notify history", icon = "󰂱", color = "yellow" },
				{ pattern = "markview", icon = "󰽛", color = "blue" },
				{ pattern = "color", icon = "󰏘", color = "yellow" },
				{ pattern = "toggle", icon = "󰔡", color = "yellow" },
				{ pattern = "focus", icon = "󱋱", color = "azure" },
				{ pattern = "fold", icon = "󰡏", color = "azure" },
				{ pattern = "ufo", icon = "󰁃", color = "azure" },
				{ pattern = "tab", icon = "󰓩", color = "azure" },
				{ pattern = "window", icon = "󱂬", color = "azure" },
				{ pattern = "split", icon = "󰤻", color = "azure" },
				{ pattern = "resize", icon = "󰙖", color = "azure" },
				{ pattern = "swap buffer", icon = "󰓡", color = "azure" },
				{ pattern = "delete buffer", icon = "󰆓", color = "red" },
				{ pattern = "scroll preview", icon = "󰆿", color = "azure" },
				{ pattern = "navigate", icon = "󱋱", color = "azure" },
				{ pattern = "hover doc", icon = "󰋖", color = "blue" },
				{ pattern = "quickfix", icon = "󰁨", color = "yellow" },
				-- ── Motion / Editing ───────────────────────────────────────
				{ pattern = "flash", icon = "⚡", color = "yellow" },
				{ pattern = "surround", icon = "󰅪", color = "cyan" },
				{ pattern = "comment", icon = "󰆉", color = "grey" },
				{ pattern = "treesj", icon = "󰗈", color = "blue" },
				{ pattern = "treewalker", icon = "󰙅", color = "blue" },
				{ pattern = "multiple.*cursor", icon = "󰇀", color = "purple" },
				{ pattern = "^mc ", icon = "󰇀", color = "purple" },
				{ pattern = "^MC ", icon = "󰇀", color = "purple" },
				{ pattern = "align cursor", icon = "󰉶", color = "purple" },
				{ pattern = "sequence increment", icon = "󰐖", color = "purple" },
				{ pattern = "sequence decrement", icon = "󰍴", color = "purple" },
				{ pattern = "split cursor", icon = "󰇘", color = "purple" },
				{ pattern = "match.*cursor", icon = "󰱼", color = "purple" },
				{ pattern = "restore cursor", icon = "󰑖", color = "purple" },
				{ pattern = "spider", icon = "󰸱", color = "cyan" },
				{ pattern = "emmet", icon = "󰅴", color = "green" },
				{ pattern = "move line", icon = "󰜸", color = "azure" },
				{ pattern = "paste", icon = "󰅍", color = "azure" },
				{ pattern = "^swap ", icon = "󰓡", color = "cyan" },
				{ pattern = "select ", icon = "󰒉", color = "cyan" },
				{ pattern = "ts repeat", icon = "󰑖", color = "blue" },
				{ pattern = "executable", icon = "󰒃", color = "green" },
				{ pattern = "make file", icon = "󰒃", color = "green" },
				{ pattern = "quit all", icon = "󰗼", color = "red" },
				{ pattern = "blink on yank", icon = "󰸱", color = "yellow" },
				-- ── File / Dirs ────────────────────────────────────────────
				{ pattern = "recent files", icon = "󱋡", color = "blue" },
				{ pattern = "recent", icon = "󱋡", color = "blue" },
				{ pattern = "file system", icon = "󰝰", color = "green" },
				{ pattern = "auto.create.*dir", icon = "󱧃", color = "green" },
				-- ── Quickfix / Loclist ─────────────────────────────────────
				{ pattern = "location list", icon = "󰁨", color = "yellow" },
				{ pattern = "loclist", icon = "󰁨", color = "yellow" },
				-- ── Live Server ────────────────────────────────────────────
				{ pattern = "live server", icon = "󰋗", color = "green" },
				-- ── Mason ─────────────────────────────────────────────────
				{ pattern = "^mason$", icon = "󱌣", color = "blue" },
				-- ── Misc ───────────────────────────────────────────────────
				{ pattern = "lazy$", icon = "󰒲", color = "purple" },
				{ pattern = "octo", icon = "󰊤", color = "grey" },
				{ pattern = "grug", icon = "󰍫", color = "blue" },
				{ pattern = "dap ui", icon = "󰃤", color = "purple" },
				-- ── Built-in operators (desc from which-key presets.lua) ───
				{ pattern = "^Uppercase$", icon = "󰬴", color = "yellow" },
				{ pattern = "^Lowercase$", icon = "󰬵", color = "yellow" },
				{ pattern = "^Toggle case$", icon = "󰬴", color = "yellow" },
				{ pattern = "^Format$", icon = "󰉢", color = "blue" },
				{ pattern = "^Replace$", icon = "󰑕", color = "yellow" },
				{ pattern = "^Visual Line$", icon = "󰒉", color = "cyan" },
				{ pattern = "^Visual$", icon = "󰒉", color = "cyan" },
				{ pattern = "^Yank$", icon = "󰅍", color = "azure" },
				{ pattern = "^Change$", icon = "󰏫", color = "orange" },
				{ pattern = "^Delete$", icon = "󰆓", color = "red" },
				{ pattern = "^Indent left$", icon = "󰉶", color = "azure" },
				{ pattern = "^Indent right$", icon = "󰉶", color = "azure" },
				{ pattern = "^Create fold$", icon = "󰡏", color = "azure" },
				{ pattern = "^Run program$", icon = "󰆍", color = "green" },
				-- ── Built-in motions ───────────────────────────────────────
				{ pattern = "^First line$", icon = "󰒮", color = "azure" },
				{ pattern = "^Last line$", icon = "󰒯", color = "azure" },
				{ pattern = "^End of line$", icon = "󰜴", color = "azure" },
				{ pattern = "^Start of line", icon = "󰜲", color = "azure" },
				{ pattern = "^Left$", icon = "󰁍", color = "azure" },
				{ pattern = "^Right$", icon = "󰁔", color = "azure" },
				{ pattern = "^Up$", icon = "󰁝", color = "azure" },
				{ pattern = "^Down$", icon = "󰁗", color = "azure" },
				{ pattern = "word$", icon = "󰜿", color = "azure" },
				{ pattern = "WORD$", icon = "󰜿", color = "azure" },
				{ pattern = "^Move to ", icon = "⚡", color = "yellow" },
				{ pattern = "^Move before ", icon = "⚡", color = "yellow" },
				{ pattern = "empty line$", icon = "󰜵", color = "azure" },
				{ pattern = "^Search forward$", icon = "󰱼", color = "blue" },
				{ pattern = "^Search backward$", icon = "󰱼", color = "blue" },
				{ pattern = "^Matching", icon = "󰅪", color = "cyan" },
				{ pattern = "Home line of window", icon = "󰒮", color = "azure" },
				{ pattern = "Last line of window", icon = "󰒯", color = "azure" },
				{ pattern = "Middle line of window", icon = "󰆿", color = "azure" },
				{ pattern = "^Next ftFT$", icon = "⚡", color = "yellow" },
				{ pattern = "^Prev ftFT$", icon = "⚡", color = "yellow" },
				-- ── z-prefix (fold / view) ─────────────────────────────────
				{ pattern = " fold", icon = "󰡏", color = "azure" },
				{ pattern = "fold ", icon = "󰡏", color = "azure" },
				{ pattern = "this line$", icon = "󰆿", color = "azure" },
				{ pattern = "Spelling suggestion", icon = "󰓆", color = "yellow" },
				{ pattern = "Half screen", icon = "󰜱", color = "azure" },
				{ pattern = "Show cursor line", icon = "󰆿", color = "azure" },
				{ pattern = "Update folds", icon = "󰡏", color = "azure" },
				{ pattern = "Mark word as bad", icon = "󰓆", color = "red" },
				{ pattern = "Add word to spell", icon = "󰓆", color = "green" },
				-- ── g-prefix ───────────────────────────────────────────────
				{ pattern = "Go to file", icon = "󰈞", color = "blue" },
				{ pattern = "Go to last insert", icon = "󰌑", color = "azure" },
				{ pattern = "Last visual selection", icon = "󰒉", color = "cyan" },
				{ pattern = "Open file with system", icon = "󰖟", color = "blue" },
				{ pattern = "tab page$", icon = "󰓩", color = "azure" },
				{ pattern = "Search.*and select", icon = "󰱼", color = "blue" },
				{ pattern = "change list$", icon = "󰋚", color = "purple" },
				{ pattern = "Cycle backwards", icon = "󰑖", color = "azure" },
				{ pattern = "unmatched group", icon = "󰅪", color = "cyan" },
				{ pattern = "method start", icon = "󰊕", color = "blue" },
				{ pattern = "method end", icon = "󰊕", color = "blue" },
				{ pattern = "misspelled word", icon = "󰓆", color = "yellow" },
				-- ── <C-w> window management ────────────────────────────────
				{ pattern = "Increase height", icon = "󰙖", color = "azure" },
				{ pattern = "Increase width", icon = "󰙖", color = "azure" },
				{ pattern = "Decrease height", icon = "󰙕", color = "azure" },
				{ pattern = "Decrease width", icon = "󰙕", color = "azure" },
				{ pattern = "Equally high and wide", icon = "󱂬", color = "azure" },
				{ pattern = "Max out", icon = "󰈈", color = "azure" },
				{ pattern = "Go to the.*window", icon = "󱋱", color = "azure" },
				{ pattern = "Split window", icon = "󰤻", color = "azure" },
				{ pattern = "Close all other windows", icon = "󰆓", color = "red" },
				{ pattern = "Quit a window", icon = "󰆓", color = "red" },
				{ pattern = "Switch windows", icon = "󰓡", color = "azure" },
				{ pattern = "Swap current with next", icon = "󰓡", color = "azure" },
				{ pattern = "Move window to far", icon = "󰈈", color = "azure" },
				{ pattern = "Break out into a new tab", icon = "󰓩", color = "azure" },
				-- ── Broad catch-alls (must stay last) ─────────────────────
				{ pattern = "^next ", icon = "󰜴", color = "green" },
				{ pattern = "^prev ", icon = "󰜲", color = "red" },
			},
		},
		win = {
			border = "rounded",
			title_pos = "center", -- prevents icon clipping against the ╭ corner
			padding = { 1, 2 },
			width = { min = 30, max = 0.4 },
		},
		-- Suppress which-key in UI panels / tool windows where it adds noise
		disable = {
			ft = {
				"neo-tree",
				"OverseerList",
				"OverseerForm",
				"OverseerOutput",
				"dapui_hover",
				"dapui_scopes",
				"dapui_console",
				"dapui_breakpoints",
				"dapui_stacks",
				"dapui_watches",
				"neotest-output",
				"neotest-summary",
				"neotest-output-panel",
				"trouble",
				"lazy",
				"mason",
				"codediff-explorer",
				"codediff-history",
			},
			bt = { "terminal" },
		},
		-- Group labels derived from every keymap in this config.
		-- No hardcoded glyphs — mini.icons (lazy=false) resolves icons automatically.
		spec = {
			-- ── Leader prefixes (normal mode) ─────────────────────────────
			{ "<leader>f", group = "Find/Files", icon = { icon = "󰍉", color = "blue" } },
			{ "<leader>g", group = "Git", icon = { icon = "󰊢", color = "orange" } },
			{ "<leader>gc", group = "Git Conflict", icon = { icon = "󰩹", color = "red" } },
			{ "<leader>gw", group = "Git Signs/Hunks", icon = { icon = "󰊢", color = "orange" } },
			{ "<leader>s", group = "Search/Replace", icon = { icon = "󰱼", color = "blue" } },
			{ "<leader>d", group = "Diagnostics/DAP", icon = { icon = "󰒡", color = "red" } },
			{ "<leader>c", group = "Code/AI", icon = { icon = "󰘦", color = "green" } },
			{ "<leader>r", group = "HTTP/Rename", icon = { icon = "󰖟", color = "blue" } },
			{ "<leader>u", group = "UI/Debug", icon = { icon = "󰒓", color = "purple" } },
			{ "<leader>w", group = "Window/Worktree", icon = { icon = "󱂬", color = "azure" } },
			{ "<leader>b", group = "Buffer/Breakpoint", icon = { icon = "󰆊", color = "orange" } },
			{ "<leader>T", group = "Test/Todo", icon = { icon = "󰙨", color = "green" } },
			{ "<leader>i", group = "REPL", icon = { icon = "󰘞", color = "cyan" } },
			{ "<leader>h", group = "Help/History", icon = { icon = "󰋖", color = "azure" } },
			{ "<leader>n", group = "Notify/Swap", icon = { icon = "󰒭", color = "yellow" } },
			{ "<leader>p", group = "Swap Prev", icon = { icon = "󰒮", color = "yellow" } },
			{ "<leader>l", group = "Lazy/LazyGit", icon = { icon = "󰒲", color = "purple" } },
			{ "<leader>m", group = "Multi-Cursor", icon = { icon = "󰇀", color = "purple" } },
			{ "<leader>e", group = "Explorer", icon = { icon = "󰙅", color = "green" } },
			{ "<leader>v", group = "Trouble", icon = { icon = "󰒡", color = "red" } },
			{ "<leader>o", group = "Overseer", icon = { icon = "󰑮", color = "yellow" } },
			{ "<leader>t", group = "Tabs", icon = { icon = "󰓩", color = "azure" } },
			{ "<leader>tm", group = "Tab Move", icon = { icon = "󰒺", color = "azure" } },
			{ "<leader>O", group = "Octo", icon = { icon = "󰊤", color = "grey" } },
			{ "<leader>D", group = "Database", icon = { icon = "󰆼", color = "cyan" } },
			{ "<leader>q", group = "Quit", icon = { icon = "󰗼", color = "red" } },
			{ "<leader>x", group = "Utils/Execute", icon = { icon = "󰒃", color = "green" } },
			-- ── Navigation prefixes ───────────────────────────────────────
			{ "]", group = "Next", icon = { icon = "󰜴", color = "green" } },
			{ "[", group = "Prev", icon = { icon = "󰜲", color = "red" } },
			-- ── Operator prefixes (normal + visual) ───────────────────────
			{ "gz", group = "Surround", mode = { "n", "v" }, icon = { icon = "󰅪", color = "cyan" } },
			{ "gc", group = "Comment", mode = { "n", "v" }, icon = { icon = "󰆉", color = "grey" } },
			{ "g", group = "Go to / Actions", icon = { icon = "󰆤", color = "azure" } },
			{ "z", group = "Fold / View", icon = { icon = "󰡏", color = "azure" } },
			-- ── Visual-mode leader groups ─────────────────────────────────
			-- These duplicate the normal-mode groups so which-key shows group
			-- names (instead of "N Keymaps") when <leader> is pressed in visual mode.
			{ "<leader>f", group = "Find/Files", mode = { "v" }, icon = { icon = "󰍉", color = "blue" } },
			{ "<leader>g", group = "Git", mode = { "v" }, icon = { icon = "󰊢", color = "orange" } },
			{ "<leader>c", group = "Code/AI", mode = { "v" }, icon = { icon = "󰘦", color = "green" } },
			{ "<leader>m", group = "Multi-Cursor", mode = { "v", "x" }, icon = { icon = "󰇀", color = "purple" } },
		},
	},
}
