return {
  "luk400/vim-jukit",
  keys = {
    {
      "<leader>jjo",
      "<cmd>call jukit#splits#output()<CR>",
      description = "Jukit Splits Output",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jjh",
      "<cmd>call jukit#splits#history()<CR>",
      description = "Jukit Splits History",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>joh",
      "<cmd>call jukit#splits#output_and_history()<CR>",
      description = "Jukit Splits Output & History",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jco",
      "<cmd>call jukit#splits#close_output_split()<CR>",
      description = "Jukit Splits Close Output",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jch",
      "<cmd>call jukit#splits#close_history()<CR>",
      description = "Jukit Splits Close History",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jca",
      "<cmd>call jukit#splits#close_output_and_history(1)<CR>",
      description = "Jukit Splits Close Ouput & History",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jhj",
      "<cmd>call jukit#splits#out_hist_scroll(1)<CR>",
      description = "Jukit Splits Scroll Down",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jhk",
      "<cmd>call jukit#splits#out_hist_scroll(0)<CR>",
      description = "Jukit Splits Scroll Up",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jht",
      "<cmd>call jukit#splits#toggle_auto_hist()<CR>",
      description = "Jukit Toggle Auto History",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jcc",
      "<cmd>call jukit#cells#create_below(0)<CR>",
      description = "Jukit Cells Create Below",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jcC",
      "<cmd>call jukit#cells#create_above(0)<CR>",
      description = "Jukit Cells Create Above",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jct",
      "<cmd>call jukit#cells#create_below(1)<CR>",
      description = "Jukit Cells Create Text Below",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jcT",
      "<cmd>call jukit#cells#create_above(1)<CR>",
      description = "Jukit Cells Create Text Above",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jcd",
      "<cmd>call jukit#cells#delete()<CR>",
      description = "Jukit Cells Delete",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jcm",
      "<cmd>call jukit#cells#merge_below()<CR>",
      description = "Jukit Cells Merge Below",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jcM",
      "<cmd>call jukit#cells#merge_above()<CR>",
      description = "Jukit Cells Merge Above",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jck",
      "<cmd>call jukit#cells#move_up()<CR>",
      description = "Jukit Cells Move Up",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jcj",
      "<cmd>call jukit#cells#move_down()<CR>",
      description = "Jukit Cells Move Down",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>JJ",
      "<cmd>call jukit#cells#jump_to_next_cell()<CR>",
      description = "Jukit Cells Jump To Next",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>KK",
      "<cmd>call jukit#cells#jump_to_previous_cell()<CR>",
      description = "Jukit Cells Jump To Previous",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jdo",
      "<cmd>call jukit#cells#delete_outputs(0)<CR>",
      description = "Jukit Delete Output Cell",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jd",
      "<cmd>call jukit#cells#delete_outputs(1)<CR>",
      description = "Jukit Delete Output Text",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jss",
      "<cmd>call jukit#send#section(1)<CR>",
      description = "Jukit Send Section",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jsl",
      "<cmd>call jukit#send#line()<CR>",
      description = "Jukit Send Line",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jss",
      { v = "<cmd>call jukit#send#selection()<CR>" },
      description = "Jukit Send Selection",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jsu",
      "<cmd>call jukit#send#until_current_section()<CR>",
      description = "Jukit Send Until Current Section",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jsa",
      "<cmd>call jukit#send#all()<CR>",
      description = "Jukit Send All",
      opts = { noremap = true, silent = true },
    },
    {
      "<leader>jcv",
      "<cmd>call jukit#convert#notebook_convert('jupyter-notebook')<CR>",
      description = "Jukit Covert",
      opts = { noremap = true, silent = true },
    },
  },
}
