return {
	"folke/lazydev.nvim",
	ft = "lua",
	opts = {
		debug = false,
		library = {
			"luvit-meta/library",
			"lazy.nvim",
			"mason.nvim",
			"mason-lspconfig.nvim",
			"mason-tool-installer.nvim",
			"nvim-lspconfig",
			"lspsaga.nvim",
			"nvim-treesitter",
			"nvim-cmp",
			"cmp-nvim-lsp",
			"conform.nvim",
			"nvim-lint",
			"noice.nvim",
			"neo-tree.nvim",
			"telescope.nvim",
			"legendary.nvim",
			"toggleterm.nvim",
			"catppuccin",
			"plenary.nvim",
			"neodev.nvim",
			"neotest",
			"fidget.nvim",
			"alpha-nvim",
			"nvim-web-devicons",
			"lualine.nvim",
			"nvim-various-textobjs",
			"obsidian.nvim",
			"diffview.nvim",
			"neorg",
			"statuscol.nvim",
			"neotab.nvim",
			"nvim-ufo",
		},
		enabled = function(root_dir)
			return true
		end,
		cmp = true,
	},
	dependencies = {
		{ "Bilal2453/luvit-meta", lazy = true },
	},
}
